version: '3.3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:11.6.2-ce.0'
    restart: always
    hostname: 'localhost'
    ports:
      - "8929:80"
      - "2289:22"
    volumes:
    # mkdir -p ./gitlab/etc/gitlab ./gitlab/var/log/gitlab ./gitlab/var/opt/gitlab
      - "./gitlab/etc/gitlab:/etc/gitlab"
      - "./gitlab/var/log/gitlab:/var/log/gitlab"
      - "./gitlab/var/opt/gitlab:/var/opt/gitlab"
